version: '2'
volumes:
    catholingodata:
services:
    catholingo:
      container_name: "catholingo"
      build: .
      restart: always
      links:
        - db
        - redis
      environment:
          DATABASE: mysql://root:catholingo@db/catholingo
          CHANNELS: "#catholingo"
          REDIS_HOST: "redis"
    db:
      container_name: "catholingo_db"
      restart: always
      image: "mysql:latest"
      volumes:
        - catholingodata:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: catholingo
        MYSQL_DATABASE: catholingo
    redis:
        container_name: "catholingo_redis"
        restart: always
        image: "redis:latest"
