catholingo:
  build: .
  container_name: "catholingo"
  restart: always
  links:
    - db
  volumes:
    - .:/catholingo
  environment:
      DATABASE: mysql://root:catholingo@db/catholingo
      CHANNELS: "#salsifis #amdo"
db:
  container_name: "catholingo_db"
  restart: always
  image: "mysql:latest"
  volumes:
    - catholingodata:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: catholingo
    MYSQL_DATABASE: catholingo
