version: '2'
volumes:
    catholingodata:
services:
    catholingo:
      container_name: "catholingo"
      build: .
      restart: always
      links:
        - db
        - redis
      environment:
          DATABASE: mysql://root:catholingo@db/catholingo
          CHANNELS: "#catholingo"
          REDIS_HOST: "redis"
          DEBUG: "1"
    db:
      container_name: "catholingo_db"
      restart: always
      image: "mysql:latest"
      volumes:
        - catholingodata:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: catholingo
        MYSQL_DATABASE: catholingo
    redis:
        container_name: "catholingo_redis"
        restart: always
        image: "redis:latest"
    ms_speech:
        container_name: "catholingo_speech"
        build:
            context: .
            dockerfile: ./speech.Dockerfile
        restart: always
        links:
          - db
          - redis
        environment:
            DATABASE: mysql://root:catholingo@db/catholingo
            REDIS_HOST: "redis"
            DEBUG: "1"
    ms_admin:
        container_name: "catholingo_admin"
        build:
            context: .
            dockerfile: ./admin.Dockerfile
        restart: always
        links:
          - db
          - redis
        environment:
            DATABASE: mysql://root:catholingo@db/catholingo
            REDIS_HOST: "redis"
            DEBUG: "1"
    ms_messenger:
        container_name: "catholingo_messenger"
        build:
            context: .
            dockerfile: ./messenger.Dockerfile
        restart: always
        links:
          - redis
        environment:
            REDIS_HOST: "redis"
            DEBUG: "1"
    ms_hue:
        container_name: "catholingo_hue"
        build:
            context: .
            dockerfile: ./hue.Dockerfile
        restart: always
        links:
          - redis
        environment:
            REDIS_HOST: "redis"
            DEBUG: "1"
